# Generated by Django 5.2.8 on 2025-11-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
