# Generated by Django 5.2.8 on 2025-11-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="boolean_field",
            new_name="is_done",
        ),
    ]
